# Generated by Django 4.1.2 on 2023-02-15 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('descricao', models.CharField(max_length=400)),
                ('data_criacao', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Já Vi', 'Já Vi'), ('Quero Ver', 'Quero Ver')], default='Já Vi', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Palestras',
            },
        ),
    ]
