# Generated by Django 4.1.2 on 2022-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('descricao', models.CharField(max_length=400)),
                ('data_criacao', models.DateField()),
                ('status', models.CharField(choices=[('JV', 'Já Vi'), ('QV', 'Quero Ver')], default='Já Vi', max_length=2)),
            ],
        ),
    ]
