# Generated by Django 4.1.2 on 2022-11-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palestrinhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palestras',
            options={'verbose_name_plural': 'Palestras'},
        ),
        migrations.AlterField(
            model_name='palestras',
            name='status',
            field=models.CharField(choices=[('Já Vi', 'Já Vi'), ('Quero Ver', 'Quero Ver')], default='Já Vi', max_length=10),
        ),
    ]
