# Generated by Django 4.1.2 on 2022-11-08 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palestrinhas', '0002_alter_palestras_options_alter_palestras_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestras',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palestras',
            name='data_criacao',
            field=models.DateField(auto_now=True),
        ),
    ]
